<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="2" passed="0">
  <reporter-output>
    <line>
      <![CDATA[Step 1 = Login to application at : http://172.25.50.64/account/login.aspx and loging in with incorrect credentails]]>
    </line>
    <line>
      <![CDATA[Step 1 = Login to application]]>
    </line>
  </reporter-output>
  <suite name="RegressionSuit" duration-ms="114316" started-at="2018-10-29T12:43:45Z" finished-at="2018-10-29T12:45:39Z">
    <groups>
    </groups>
    <test name="RunningOnChrome" duration-ms="114316" started-at="2018-10-29T12:43:45Z" finished-at="2018-10-29T12:45:39Z">
      <class name="AER.FMDP_Automation.tests.login.LoginTests">
        <test-method status="PASS" signature="setUp(java.lang.String, java.lang.String)[pri:0, instance:AER.FMDP_Automation.tests.login.LoginTests@7d9d1a19]" name="setUp" is-config="true" duration-ms="7257" started-at="2018-10-29T12:43:45Z" finished-at="2018-10-29T12:43:52Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[local]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:AER.FMDP_Automation.tests.login.LoginTests@7d9d1a19]" name="beforeMethod" is-config="true" duration-ms="5" started-at="2018-10-29T12:43:52Z" finished-at="2018-10-29T12:43:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="login_Failure()[pri:1, instance:AER.FMDP_Automation.tests.login.LoginTests@7d9d1a19]" name="login_Failure" duration-ms="63785" started-at="2018-10-29T12:43:52Z" finished-at="2018-10-29T12:44:56Z">
          <exception class="java.io.FileNotFoundException">
            <message>
              <![CDATA[test-output\screenshots\login_Failure_20181029_181456.png (The system cannot find the path specified)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.io.FileNotFoundException: test-output\screenshots\login_Failure_20181029_181456.png (The system cannot find the path specified)
at java.io.FileOutputStream.open0(Native Method)
at java.io.FileOutputStream.open(FileOutputStream.java:270)
at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
at com.google.common.io.Files$FileByteSink.openStream(Files.java:192)
at com.google.common.io.Files$FileByteSink.openStream(Files.java:180)
at com.google.common.io.ByteSource.copyTo(ByteSource.java:268)
at com.google.common.io.Files.copy(Files.java:319)
at utilities.SeleniumHelpers.takeScreenshot(SeleniumHelpers.java:34)
at utilities.ExceptionHandler.TakeScreenshotAndLogException(ExceptionHandler.java:25)
at AER.FMDP_Automation.tests.login.LoginTests.login_Failure(LoginTests.java:122)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.io.FileNotFoundException -->
          <reporter-output>
            <line>
              <![CDATA[Step 1 = Login to application at : http://172.25.50.64/account/login.aspx and loging in with incorrect credentails]]>
            </line>
          </reporter-output>
        </test-method> <!-- login_Failure -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:AER.FMDP_Automation.tests.login.LoginTests@7d9d1a19]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2018-10-29T12:44:56Z" finished-at="2018-10-29T12:44:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="login_ChangePassword()[pri:2, instance:AER.FMDP_Automation.tests.login.LoginTests@7d9d1a19]" name="login_ChangePassword" duration-ms="42369" started-at="2018-10-29T12:44:56Z" finished-at="2018-10-29T12:45:39Z">
          <exception class="java.io.FileNotFoundException">
            <message>
              <![CDATA[test-output\screenshots\login_ChangePassword_20181029_181539.png (The system cannot find the path specified)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.io.FileNotFoundException: test-output\screenshots\login_ChangePassword_20181029_181539.png (The system cannot find the path specified)
at java.io.FileOutputStream.open0(Native Method)
at java.io.FileOutputStream.open(FileOutputStream.java:270)
at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
at com.google.common.io.Files$FileByteSink.openStream(Files.java:192)
at com.google.common.io.Files$FileByteSink.openStream(Files.java:180)
at com.google.common.io.ByteSource.copyTo(ByteSource.java:268)
at com.google.common.io.Files.copy(Files.java:319)
at utilities.SeleniumHelpers.takeScreenshot(SeleniumHelpers.java:34)
at utilities.ExceptionHandler.TakeScreenshotAndLogException(ExceptionHandler.java:25)
at AER.FMDP_Automation.tests.login.LoginTests.login_ChangePassword(LoginTests.java:99)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.io.FileNotFoundException -->
          <reporter-output>
            <line>
              <![CDATA[Step 1 = Login to application]]>
            </line>
          </reporter-output>
        </test-method> <!-- login_ChangePassword -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:AER.FMDP_Automation.tests.login.LoginTests@7d9d1a19]" name="tearDown" is-config="true" duration-ms="842" started-at="2018-10-29T12:45:39Z" finished-at="2018-10-29T12:45:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- AER.FMDP_Automation.tests.login.LoginTests -->
    </test> <!-- RunningOnChrome -->
  </suite> <!-- RegressionSuit -->
</testng-results>
